#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///

"""Prepare local training configs and a launch script behind a continue gate."""

from __future__ import annotations

import argparse
import json
import os
import platform
import re
import shlex
import shutil
from pathlib import Path
from typing import Any


DEFAULT_MODEL = "Qwen/Qwen2.5-0.5B-Instruct"
DEFAULT_SYSTEM = "You are a helpful assistant."

METHOD_DEFAULTS: dict[str, dict[str, str]] = {
    "sft": {
        "train_type": "lora",
        "max_length": "2048",
        "batch_size": "1",
        "grad_acc": "4",
        "learning_rate": "5e-5",
        "epochs": "1",
        "max_steps": "24",
        "save_steps": "12",
        "eval_steps": "12",
        "logging_steps": "5",
        "lora_rank": "8",
        "extra_swift_args": "--torch_dtype bfloat16",
    },
    "dpo": {
        "train_type": "lora",
        "max_length": "2048",
        "batch_size": "1",
        "grad_acc": "4",
        "learning_rate": "1e-5",
        "epochs": "1",
        "max_steps": "24",
        "save_steps": "12",
        "eval_steps": "12",
        "logging_steps": "5",
        "lora_rank": "8",
        "beta": "0.1",
        "loss_type": "sigmoid",
        "extra_swift_args": "--torch_dtype bfloat16",
    },
    "grpo": {
        "train_type": "lora",
        "max_length": "2048",
        "batch_size": "1",
        "grad_acc": "8",
        "learning_rate": "1e-6",
        "epochs": "1",
        "max_steps": "24",
        "save_steps": "12",
        "eval_steps": "12",
        "logging_steps": "5",
        "lora_rank": "8",
        "use_vllm": "false",
        "extra_swift_args": "--torch_dtype bfloat16",
    },
}

KEY_ALIASES = {
    "learning rate": "learning_rate",
    "learning_rate": "learning_rate",
    "lr": "learning_rate",
    "学习率": "learning_rate",
    "batch size": "batch_size",
    "batch_size": "batch_size",
    "训练批大小": "batch_size",
    "批大小": "batch_size",
    "grad acc": "grad_acc",
    "grad_acc": "grad_acc",
    "gradient accumulation": "grad_acc",
    "gradient_accumulation_steps": "grad_acc",
    "梯度累积": "grad_acc",
    "epochs": "epochs",
    "epoch": "epochs",
    "轮数": "epochs",
    "max steps": "max_steps",
    "max_steps": "max_steps",
    "save steps": "save_steps",
    "save_steps": "save_steps",
    "eval steps": "eval_steps",
    "eval_steps": "eval_steps",
    "logging steps": "logging_steps",
    "logging_steps": "logging_steps",
    "max length": "max_length",
    "max_length": "max_length",
    "上下文长度": "max_length",
    "序列长度": "max_length",
    "lora rank": "lora_rank",
    "lora_rank": "lora_rank",
    "beta": "beta",
    "loss type": "loss_type",
    "loss_type": "loss_type",
    "train type": "train_type",
    "train_type": "train_type",
    "微调方式": "train_type",
    "use vllm": "use_vllm",
    "use_vllm": "use_vllm",
}


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def parse_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        raw_value = value.strip()
        try:
            parts = shlex.split(raw_value, posix=True)
            data[key.strip()] = parts[0] if len(parts) == 1 else raw_value
        except ValueError:
            data[key.strip()] = raw_value
    return data


def write_env_file(path: Path, mapping: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"{key}={shlex.quote(str(mapping.get(key, '')))}" for key in mapping if key.upper() == key]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_shell_script(path: Path, root: Path) -> None:
    required_env = (root / "configs" / "local.required.env").relative_to(root).as_posix()
    train_env = (root / "configs" / "local.train.env").relative_to(root).as_posix()
    content = "\n".join(
        [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            "",
            "# Generated by modelscope-local-trainer.",
            f"source {required_env}",
            f"source {train_env}",
            "",
            'if [[ "${LOCAL_HOST_OS}" != "linux" ]]; then',
            '  echo "LOCAL_HOST_OS must be linux before local training starts." >&2',
            "  exit 1",
            "fi",
            'if ! command -v "${SWIFT_BIN}" >/dev/null 2>&1; then',
            '  echo "Configured SWIFT_BIN is not available on this machine." >&2',
            "  exit 1",
            "fi",
            "",
            'cd "${LOCAL_WORKDIR}"',
            'export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES}"',
            'export NPROC_PER_NODE="${NPROC_PER_NODE}"',
            "",
            'CMD=("${SWIFT_BIN}")',
            'if [[ "${TRAINER_METHOD}" == "sft" ]]; then',
            '  CMD+=("sft")',
            "else",
            '  CMD+=("rlhf" "--rlhf_type" "${TRAINER_METHOD}")',
            "fi",
            'CMD+=(',
            '  "--model" "${MODEL_ID}"',
            '  "--dataset" "${TRAIN_DATASET}"',
            '  "--output_dir" "${OUTPUT_DIR}"',
            '  "--train_type" "${TRAIN_TYPE}"',
            '  "--max_length" "${MAX_LENGTH}"',
            '  "--per_device_train_batch_size" "${BATCH_SIZE}"',
            '  "--gradient_accumulation_steps" "${GRAD_ACC}"',
            '  "--learning_rate" "${LEARNING_RATE}"',
            '  "--num_train_epochs" "${EPOCHS}"',
            '  "--max_steps" "${MAX_STEPS}"',
            '  "--save_steps" "${SAVE_STEPS}"',
            '  "--eval_steps" "${EVAL_STEPS}"',
            '  "--logging_steps" "${LOGGING_STEPS}"',
            '  "--system" "${SYSTEM_PROMPT}"',
            ')',
            'if [[ "${TRAIN_TYPE}" == "lora" || "${TRAIN_TYPE}" == "qlora" ]]; then',
            '  CMD+=("--lora_rank" "${LORA_RANK}")',
            "fi",
            'if [[ -n "${VALID_DATASET:-}" ]]; then',
            '  CMD+=("--val_dataset" "${VALID_DATASET}")',
            "fi",
            'if [[ "${TRAINER_METHOD}" == "dpo" ]]; then',
            '  CMD+=("--beta" "${BETA}" "--loss_type" "${LOSS_TYPE}")',
            "fi",
            'if [[ "${TRAINER_METHOD}" == "grpo" ]]; then',
            '  CMD+=("--use_vllm" "${USE_VLLM}")',
            "fi",
            'if [[ -n "${EXTRA_SWIFT_ARGS:-}" ]]; then',
            '  # shellcheck disable=SC2206',
            '  EXTRA_ARGS=(${EXTRA_SWIFT_ARGS})',
            '  CMD+=("${EXTRA_ARGS[@]}")',
            "fi",
            "",
            '"${CMD[@]}"',
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | 0o111)


def detect_local_runtime() -> dict[str, Any]:
    system = platform.system().lower()
    return {
        "system": system,
        "is_linux": system == "linux",
        "swift_on_path": shutil.which("swift") is not None,
        "nvidia_smi_on_path": shutil.which("nvidia-smi") is not None,
    }


def build_required_env(root: Path, runtime: dict[str, Any]) -> dict[str, str]:
    existing = parse_env_file(root / "configs" / "local.required.env")
    return {
        "LOCAL_HOST_OS": existing.get("LOCAL_HOST_OS", "linux" if runtime["is_linux"] else runtime["system"] or "linux"),
        "LOCAL_WORKDIR": existing.get("LOCAL_WORKDIR", str(root)),
        "SWIFT_BIN": existing.get("SWIFT_BIN", "swift"),
        "PYTHON_BIN": existing.get("PYTHON_BIN", "python"),
        "CUDA_VISIBLE_DEVICES": existing.get("CUDA_VISIBLE_DEVICES", os.environ.get("CUDA_VISIBLE_DEVICES", "0")),
        "NPROC_PER_NODE": existing.get("NPROC_PER_NODE", os.environ.get("NPROC_PER_NODE", "1")),
        "TRAIN_LOG_DIR": existing.get("TRAIN_LOG_DIR", str(root / "outputs" / "logs")),
        "TRAIN_HOST_NOTE": existing.get("TRAIN_HOST_NOTE", "review_then_continue"),
    }


def write_jsonl_if_missing(path: Path, rows: list[dict[str, Any]], force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(json.dumps(row, ensure_ascii=False) for row in rows) + "\n",
        encoding="utf-8",
    )
    return True


def normalize_method(raw: str) -> str:
    text = raw.lower()
    if any(token in text for token in ["grpo", "rlhf", "强化学习", "reinforcement"]):
        return "grpo"
    if any(token in text for token in ["dpo", "偏好优化", "preference optimization"]):
        return "dpo"
    return "sft"


def detect_train_type(request: str) -> str:
    lowered = request.lower()
    if "qlora" in lowered:
        return "qlora"
    if "全参数" in request or "full parameter" in lowered or re.search(r"\bfull\b", lowered):
        return "full"
    return "lora"


def is_probable_repo_id(token: str) -> bool:
    lowered = token.lower()
    if token.startswith((".", "/", "~")):
        return False
    bad_suffixes = (
        ".json",
        ".jsonl",
        ".csv",
        ".tsv",
        ".parquet",
        ".txt",
        ".jpg",
        ".jpeg",
        ".png",
        ".webp",
    )
    return not lowered.endswith(bad_suffixes)


def extract_repo_like(request: str, keywords: list[str]) -> str:
    lowered = request.lower()
    repo_pat = re.compile(r"(?<![/.\w-])([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+(?:#[A-Za-z0-9_.-]+)?)")
    for keyword in keywords:
        idx = lowered.find(keyword.lower())
        if idx == -1:
            continue
        snippet = request[idx : idx + 160]
        match = repo_pat.search(snippet)
        if match and is_probable_repo_id(match.group(1)):
            return match.group(1)
    return ""


def extract_path_like(request: str, keywords: list[str]) -> str:
    lowered = request.lower()
    path_pat = re.compile(
        r"(?:^|[\s'\"=：:])(?P<path>\./[^\s,，;；]+|\.\./[^\s,，;；]+|/[^\s,，;；]+|~/[^\s,，;；]+)"
    )
    for keyword in keywords:
        idx = lowered.find(keyword.lower())
        if idx == -1:
            continue
        snippet = request[idx : idx + 160]
        match = path_pat.search(snippet)
        if match:
            return match.group("path")
    return ""


def extract_first_local_path(request: str) -> str:
    path_pat = re.compile(
        r"(?:^|[\s'\"=：:])(?P<path>\./[^\s,，;；]+|\.\./[^\s,，;；]+|/[^\s,，;；]+|~/[^\s,，;；]+)"
    )
    match = path_pat.search(request)
    return match.group("path") if match else ""


def extract_scalar_params(request: str) -> dict[str, str]:
    params: dict[str, str] = {}
    pattern = re.compile(
        r"(?P<key>learning rate|learning_rate|lr|学习率|batch size|batch_size|训练批大小|批大小|"
        r"grad acc|grad_acc|gradient accumulation|gradient_accumulation_steps|梯度累积|"
        r"epochs|epoch|轮数|max steps|max_steps|save steps|save_steps|eval steps|eval_steps|"
        r"logging steps|logging_steps|max length|max_length|上下文长度|序列长度|lora rank|lora_rank|"
        r"beta|loss type|loss_type|train type|train_type|微调方式|use vllm|use_vllm)"
        r"\s*[:=：]\s*(?P<value>[^\s,，;；]+)",
        re.IGNORECASE,
    )
    for match in pattern.finditer(request):
        key = KEY_ALIASES[match.group("key").lower()]
        params[key] = match.group("value")
    return params


def build_messages(user_text: str, assistant_text: str) -> list[dict[str, str]]:
    return [
        {"role": "system", "content": DEFAULT_SYSTEM},
        {"role": "user", "content": user_text},
        {"role": "assistant", "content": assistant_text},
    ]


def default_rows(method: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    if method == "dpo":
        train = [
            {
                "messages": build_messages(
                    "Rewrite this message in a more professional tone: send me the file now.",
                    "Could you please send me the file when you have a moment?",
                ),
                "rejected_response": "Send me the file now.",
            }
        ]
        valid = [
            {
                "messages": build_messages(
                    "Answer briefly: why are unit tests useful?",
                    "Unit tests catch regressions early and make refactoring safer.",
                ),
                "rejected_response": "They are useful.",
            }
        ]
        return train, valid

    if method == "grpo":
        train = [
            {
                "messages": [
                    {"role": "system", "content": "You are a careful math assistant."},
                    {"role": "user", "content": "Compute 9 * 8. Final answer only."},
                ],
                "solution": "72",
            }
        ]
        valid = [
            {
                "messages": [
                    {"role": "system", "content": "You are a careful math assistant."},
                    {"role": "user", "content": "What is 15 - 6? Final answer only."},
                ],
                "solution": "9",
            }
        ]
        return train, valid

    train = [
        {
            "messages": build_messages(
                "Explain supervised fine-tuning in one sentence.",
                "Supervised fine-tuning adapts a base model on example inputs and target outputs.",
            )
        }
    ]
    valid = [
        {
            "messages": build_messages(
                "Give one reason for using LoRA.",
                "LoRA reduces training cost by updating a small set of adapter weights.",
            )
        }
    ]
    return train, valid


def ensure_default_dataset(root: Path, method: str, force: bool) -> dict[str, Any]:
    train_rows, valid_rows = default_rows(method)
    data_dir = root / "data" / "local" / method
    train_path = data_dir / "train.jsonl"
    valid_path = data_dir / "valid.jsonl"
    changed = []
    if write_jsonl_if_missing(train_path, train_rows, force):
        changed.append(str(train_path))
    if write_jsonl_if_missing(valid_path, valid_rows, force):
        changed.append(str(valid_path))
    return {
        "train_path": train_path,
        "valid_path": valid_path,
        "changed_files": changed,
    }


def build_request(args: argparse.Namespace) -> dict[str, Any]:
    request = (args.request or "").strip()
    method = args.method or normalize_method(request)
    model_id = args.model or extract_repo_like(request, ["模型", "model", "base model", "基础模型"])
    if not model_id:
        model_id = DEFAULT_MODEL

    dataset = args.dataset or extract_repo_like(request, ["数据集", "dataset"])
    if not dataset:
        dataset = extract_path_like(request, ["数据集", "dataset", "训练集"])
    if not dataset:
        dataset = extract_first_local_path(request)

    params = METHOD_DEFAULTS[method].copy()
    params.update(extract_scalar_params(request))
    if "train_type" not in params or not params["train_type"]:
        params["train_type"] = detect_train_type(request)
    elif params["train_type"].lower() not in {"lora", "qlora", "full"}:
        params["train_type"] = detect_train_type(request)

    output_dir = args.output_dir or f"./outputs/local-{method}"
    return {
        "request_text": request,
        "method": method,
        "model_id": model_id,
        "dataset": dataset,
        "output_dir": output_dir,
        "system_prompt": DEFAULT_SYSTEM,
        "params": params,
    }


def build_local_env(request_cfg: dict[str, Any], train_dataset: str, valid_dataset: str | None) -> dict[str, str]:
    params = request_cfg["params"]
    env = {
        "MODEL_ID": request_cfg["model_id"],
        "TRAINER_METHOD": request_cfg["method"],
        "TRAIN_DATASET": train_dataset,
        "OUTPUT_DIR": request_cfg["output_dir"],
        "TRAIN_TYPE": params["train_type"],
        "MAX_LENGTH": params["max_length"],
        "BATCH_SIZE": params["batch_size"],
        "GRAD_ACC": params["grad_acc"],
        "LEARNING_RATE": params["learning_rate"],
        "EPOCHS": params["epochs"],
        "MAX_STEPS": params["max_steps"],
        "SAVE_STEPS": params["save_steps"],
        "EVAL_STEPS": params["eval_steps"],
        "LOGGING_STEPS": params["logging_steps"],
        "LORA_RANK": params["lora_rank"],
        "SYSTEM_PROMPT": request_cfg["system_prompt"],
        "EXTRA_SWIFT_ARGS": params["extra_swift_args"],
        "LOCAL_TRAIN_NOT_EXECUTED": "true",
    }
    if valid_dataset:
        env["VALID_DATASET"] = valid_dataset
    if request_cfg["method"] == "dpo":
        env["BETA"] = params["beta"]
        env["LOSS_TYPE"] = params["loss_type"]
    if request_cfg["method"] == "grpo":
        env["USE_VLLM"] = params["use_vllm"]
    return env


def build_command_preview(env: dict[str, str]) -> str:
    method = env["TRAINER_METHOD"].lower()
    if method == "sft":
        cmd = [
            "swift",
            "sft",
            "--model",
            env["MODEL_ID"],
            "--dataset",
            env["TRAIN_DATASET"],
            "--output_dir",
            env["OUTPUT_DIR"],
        ]
    else:
        cmd = [
            "swift",
            "rlhf",
            "--rlhf_type",
            method,
            "--model",
            env["MODEL_ID"],
            "--dataset",
            env["TRAIN_DATASET"],
            "--output_dir",
            env["OUTPUT_DIR"],
        ]
    cmd.extend(
        [
            "--train_type",
            env["TRAIN_TYPE"],
            "--max_length",
            env["MAX_LENGTH"],
            "--per_device_train_batch_size",
            env["BATCH_SIZE"],
            "--gradient_accumulation_steps",
            env["GRAD_ACC"],
            "--learning_rate",
            env["LEARNING_RATE"],
            "--num_train_epochs",
            env["EPOCHS"],
            "--max_steps",
            env["MAX_STEPS"],
            "--save_steps",
            env["SAVE_STEPS"],
            "--eval_steps",
            env["EVAL_STEPS"],
            "--logging_steps",
            env["LOGGING_STEPS"],
            "--system",
            env["SYSTEM_PROMPT"],
        ]
    )
    if env["TRAIN_TYPE"] in {"lora", "qlora"}:
        cmd.extend(["--lora_rank", env["LORA_RANK"]])
    if env.get("VALID_DATASET"):
        cmd.extend(["--val_dataset", env["VALID_DATASET"]])
    if method == "dpo":
        cmd.extend(["--beta", env["BETA"], "--loss_type", env["LOSS_TYPE"]])
    if method == "grpo":
        cmd.extend(["--use_vllm", env["USE_VLLM"]])
    extra = env.get("EXTRA_SWIFT_ARGS", "").strip()
    rendered = " ".join(cmd)
    if extra:
        rendered = f"{rendered} {extra}"
    return rendered


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare local training configs and a launch script")
    parser.add_argument("--request", default="", help="Natural-language training request")
    parser.add_argument("--root", default=".", help="Workspace root")
    parser.add_argument("--method", choices=["sft", "dpo", "grpo"], help="Override method")
    parser.add_argument("--model", default="", help="Override model id")
    parser.add_argument("--dataset", default="", help="Override dataset id or local path")
    parser.add_argument("--output-dir", default="", help="Override output directory")
    parser.add_argument("--force", action="store_true", help="Overwrite generated local example dataset")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    request_cfg = build_request(args)
    dataset_bootstrap = None
    changed_files: list[str] = []

    if request_cfg["dataset"]:
        train_dataset = request_cfg["dataset"]
        valid_dataset = ""
    else:
        dataset_bootstrap = ensure_default_dataset(root, request_cfg["method"], force=args.force)
        changed_files.extend(dataset_bootstrap["changed_files"])
        train_dataset = dataset_bootstrap["train_path"].as_posix()
        valid_dataset = dataset_bootstrap["valid_path"].as_posix()

    env = build_local_env(request_cfg, train_dataset, valid_dataset or None)
    configs_dir = root / "configs"
    scripts_dir = root / "scripts"
    write_env_file(configs_dir / "local.train.env", env)

    command = build_command_preview(env)
    launch_path = scripts_dir / "run_local_training.sh"
    required_env = build_required_env(root, detect_local_runtime())
    write_env_file(configs_dir / "local.required.env", required_env)
    write_shell_script(launch_path, root)
    runtime = detect_local_runtime()

    plan = {
        "request": request_cfg,
        "train_dataset": train_dataset,
        "valid_dataset": valid_dataset,
        "generated_files": {
            "required_env_file": str(configs_dir / "local.required.env"),
            "env_file": str(configs_dir / "local.train.env"),
            "launch_script": str(launch_path),
        },
        "local_dataset_bootstrap": None
        if dataset_bootstrap is None
        else {
            "train_path": str(dataset_bootstrap["train_path"]),
            "valid_path": str(dataset_bootstrap["valid_path"]),
        },
        "run_command_preview": command,
        "launch_command": f"bash {launch_path.relative_to(root).as_posix()}",
        "runtime_check": runtime,
        "wait_for_continue": True,
        "continue_gate_file": str(configs_dir / "local.required.env"),
        "prepared_only": True,
        "not_executed": True,
    }
    write_json(configs_dir / "local.training.plan.json", plan)

    result = {
        "workspace_root": str(root),
        "method": request_cfg["method"],
        "model_id": request_cfg["model_id"],
        "train_dataset": train_dataset,
        "valid_dataset": valid_dataset,
        "generated_files": [
            str(configs_dir / "local.training.plan.json"),
            str(configs_dir / "local.required.env"),
            str(configs_dir / "local.train.env"),
            str(launch_path),
        ],
        "changed_files": changed_files,
        "run_command_preview": command,
        "launch_command": f"bash {launch_path.relative_to(root).as_posix()}",
        "runtime_check": runtime,
        "wait_for_continue": True,
        "continue_gate_file": str(configs_dir / "local.required.env"),
        "prepared_only": True,
        "not_executed": True,
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
